// WARNING: Here be Dragons
// This file is generated by Creer, do not modify it
// It basically sets up all the classes, interfaces, types, and what-not that
// we need for TypeScript to know the base classes, while allowing for minimal
// code for developers to be forced to fill out.

/* eslint-disable @typescript-eslint/no-empty-interface */

// base game classes
import {
    BaseAI,
    BaseGame,
    BaseGameManager,
    BaseGameObject,
    BaseGameObjectFactory,
    BaseGameSettingsManager,
    BasePlayer,
    makeNamespace,
} from "~/core/game";

// mixins
import {
    TurnBasedPlayer,
    TwoPlayerPlayer,
    mixTurnBased,
    mixTwoPlayer,
} from "~/core/game/mixins";

// extract game object constructor args
import { FirstArgumentFromConstructor } from "~/utils";

/**
 * The interface that the Player for the Spiders game
 * must implement from mixed in game logic.
 */
export interface BaseSpidersPlayer
    extends BasePlayer,
        TwoPlayerPlayer,
        TurnBasedPlayer {}

const base0 = {
    AI: BaseAI,
    Game: BaseGame,
    GameManager: BaseGameManager,
    GameObject: BaseGameObject,
    GameSettings: BaseGameSettingsManager,
};

const base1 = mixTwoPlayer(base0);
const base2 = mixTurnBased(base1);

const mixed = base2;

/** The base AI class for the Spiders game will mixin logic. */
class BaseSpidersAI extends mixed.AI {}

/** The base Game class for the Spiders game will mixin logic. */
class BaseSpidersGame extends mixed.Game {}

/** The base GameManager class for the Spiders game will mixin logic. */
class BaseSpidersGameManager extends mixed.GameManager {}

/** The base GameObject class for the Spiders game will mixin logic. */
class BaseSpidersGameObject extends mixed.GameObject {}

/** The base GameSettings class for the Spiders game will mixin logic. */
class BaseSpidersGameSettings extends mixed.GameSettings {}

/** The Base classes that game classes build off of. */
export const BaseClasses = {
    AI: BaseSpidersAI,
    Game: BaseSpidersGame,
    GameManager: BaseSpidersGameManager,
    GameObject: BaseSpidersGameObject,
    GameSettings: BaseSpidersGameSettings,
};

// Now all the base classes are created;
// so we can start importing/exporting the classes that need them.

/** All the possible properties for BroodMother instances. */
export interface BroodMotherProperties {
    /**
     * How many eggs the BroodMother has to spawn Spiderlings this turn.
     */
    eggs?: number;

    /**
     * How much health this BroodMother has left. When it reaches 0, she dies
     * and her owner loses.
     */
    health?: number;
}

/**
 * Argument overrides for BroodMother's consume function. If you return an
 * object of this interface from the invalidate functions, the value(s) you set
 * will be used in the actual function.
 */
export interface BroodMotherConsumeArgs {
    /**
     * The Spiderling to consume. It must be on the same Nest as
     * this BroodMother.
     */
    spiderling?: Spiderling;
}

/**
 * Argument overrides for BroodMother's spawn function. If you return an object
 * of this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface BroodMotherSpawnArgs {
    /**
     * The string name of the Spiderling class you want to Spawn. Must
     * be 'Spitter', 'Weaver', or 'Cutter'.
     */
    spiderlingType?: "Spitter" | "Weaver" | "Cutter";
}

/** All the possible properties for Cutter instances. */
export interface CutterProperties {
    /**
     * The Web that this Cutter is trying to cut. Undefined if not cutting.
     */
    cuttingWeb?: Web;
}

/**
 * Argument overrides for Cutter's cut function. If you return an object of
 * this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface CutterCutArgs {
    /**
     * The web you want to Cut. Must be connected to the Nest this Cutter is
     * currently on.
     */
    web?: Web;
}

/** All the possible properties for GameObject instances. */
export interface GameObjectProperties {}

/** All the possible properties for Nest instances. */
export interface NestProperties {
    /**
     * The Player that 'controls' this Nest as they have the most Spiders on
     * this nest.
     */
    controllingPlayer?: Player;

    /**
     * All the Spiders currently located on this Nest.
     */
    spiders?: Spider[];

    /**
     * Webs that connect to this Nest.
     */
    webs?: Web[];

    /**
     * The X coordinate of the Nest. Used for distance calculations.
     */
    x?: number;

    /**
     * The Y coordinate of the Nest. Used for distance calculations.
     */
    y?: number;
}

/** All the possible properties for Player instances. */
export interface PlayerProperties {
    /**
     * This player's BroodMother. If it dies they lose the game.
     */
    broodMother?: BroodMother;

    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other
     * language. For potential data mining purposes.
     */
    clientType?: string;

    /**
     * If the player lost the game or not.
     */
    lost?: boolean;

    /**
     * The max number of Spiderlings players can spawn.
     */
    maxSpiderlings?: number;

    /**
     * The name of the player.
     */
    name?: string;

    /**
     * The number of nests this player controls.
     */
    numberOfNestsControlled?: number;

    /**
     * This player's opponent in the game.
     */
    opponent?: Player;

    /**
     * The reason why the player lost the game.
     */
    reasonLost?: string;

    /**
     * The reason why the player won the game.
     */
    reasonWon?: string;

    /**
     * All the Spiders owned by this player.
     */
    spiders?: Spider[];

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    timeRemaining?: number;

    /**
     * If the player won the game or not.
     */
    won?: boolean;
}

/** All the possible properties for Spider instances. */
export interface SpiderProperties {
    /**
     * If this Spider is dead and has been removed from the game.
     */
    isDead?: boolean;

    /**
     * The Nest that this Spider is currently on. Undefined when moving on
     * a Web.
     */
    nest?: Nest;

    /**
     * The Player that owns this Spider, and can command it.
     */
    owner?: Player;
}

/** All the possible properties for Spiderling instances. */
export interface SpiderlingProperties {
    /**
     * When empty string this Spiderling is not busy, and can act. Otherwise a
     * string representing what it is busy with, e.g. 'Moving', 'Attacking'.
     */
    busy?:
        | ""
        | "Moving"
        | "Attacking"
        | "Strengthening"
        | "Weakening"
        | "Cutting"
        | "Spitting";

    /**
     * The Web this Spiderling is using to move. Undefined if it is not moving.
     */
    movingOnWeb?: Web;

    /**
     * The Nest this Spiderling is moving to. Undefined if it is not moving.
     */
    movingToNest?: Nest;

    /**
     * The number of Spiderlings busy with the same work this Spiderling is
     * doing, speeding up the task.
     */
    numberOfCoworkers?: number;

    /**
     * How much work needs to be done for this Spiderling to finish being busy.
     * See docs for the Work forumla.
     */
    workRemaining?: number;
}

/**
 * Argument overrides for Spiderling's attack function. If you return an object
 * of this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface SpiderlingAttackArgs {
    /**
     * The Spiderling to attack.
     */
    spiderling?: Spiderling;
}

/**
 * Argument overrides for Spiderling's move function. If you return an object
 * of this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface SpiderlingMoveArgs {
    /**
     * The Web you want to move across to the other Nest.
     */
    web?: Web;
}

/** All the possible properties for Spitter instances. */
export interface SpitterProperties {
    /**
     * The Nest that this Spitter is creating a Web to spit at, thus connecting
     * them. Undefined if not spitting.
     */
    spittingWebToNest?: Nest;
}

/**
 * Argument overrides for Spitter's spit function. If you return an object of
 * this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface SpitterSpitArgs {
    /**
     * The Nest you want to spit a Web to, thus connecting that Nest and the
     * one the Spitter is on.
     */
    nest?: Nest;
}

/** All the possible properties for Weaver instances. */
export interface WeaverProperties {
    /**
     * The Web that this Weaver is strengthening. Undefined if not
     * strengthening.
     */
    strengtheningWeb?: Web;

    /**
     * The Web that this Weaver is weakening. Undefined if not weakening.
     */
    weakeningWeb?: Web;
}

/**
 * Argument overrides for Weaver's strengthen function. If you return an object
 * of this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface WeaverStrengthenArgs {
    /**
     * The web you want to strengthen. Must be connected to the Nest
     * this Weaver is currently on.
     */
    web?: Web;
}

/**
 * Argument overrides for Weaver's weaken function. If you return an object of
 * this interface from the invalidate functions, the value(s) you set will be
 * used in the actual function.
 */
export interface WeaverWeakenArgs {
    /**
     * The web you want to weaken. Must be connected to the Nest this Weaver is
     * currently on.
     */
    web?: Web;
}

/** All the possible properties for Web instances. */
export interface WebProperties {
    /**
     * How long this Web is, i.e., the distance between its nestA and nestB.
     */
    length?: number;

    /**
     * How much weight this Web currently has on it, which is the sum of all
     * its Spiderlings weight.
     */
    load?: number;

    /**
     * The first Nest this Web is connected to.
     */
    nestA?: Nest;

    /**
     * The second Nest this Web is connected to.
     */
    nestB?: Nest;

    /**
     * All the Spiderlings currently moving along this Web.
     */
    spiderlings?: Spiderling[];

    /**
     * How much weight this Web can take before snapping and destroying itself
     * and all the Spiders on it.
     */
    strength?: number;
}

/**
 * The default args passed to a constructor function for class
 * instances of BroodMother.
 */
export type BroodMotherConstructorArgs<T extends {} = {}> = Readonly<
    SpiderArgs & BroodMotherProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Cutter.
 */
export type CutterConstructorArgs<T extends {} = {}> = Readonly<
    SpiderlingArgs & CutterProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of GameObject.
 */
export type GameObjectConstructorArgs<T extends {} = {}> = Readonly<
    GameObjectProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Nest.
 */
export type NestConstructorArgs<T extends {} = {}> = Readonly<
    NestProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Player.
 */
export type PlayerConstructorArgs<T extends {} = {}> = Readonly<
    BaseSpidersPlayer & PlayerProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Spider.
 */
export type SpiderConstructorArgs<T extends {} = {}> = Readonly<
    SpiderProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Spiderling.
 */
export type SpiderlingConstructorArgs<T extends {} = {}> = Readonly<
    SpiderArgs & SpiderlingProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Spitter.
 */
export type SpitterConstructorArgs<T extends {} = {}> = Readonly<
    SpiderlingArgs & SpitterProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Weaver.
 */
export type WeaverConstructorArgs<T extends {} = {}> = Readonly<
    SpiderlingArgs & WeaverProperties & T
>;

/**
 * The default args passed to a constructor function for class
 * instances of Web.
 */
export type WebConstructorArgs<T extends {} = {}> = Readonly<
    WebProperties & T
>;

export * from "./brood-mother";
export * from "./cutter";
export * from "./game-object";
export * from "./nest";
export * from "./player";
export * from "./spider";
export * from "./spiderling";
export * from "./spitter";
export * from "./weaver";
export * from "./web";
export * from "./game";
export * from "./game-manager";
export * from "./ai";

import { BroodMother } from "./brood-mother";
import { Cutter } from "./cutter";
import { GameObject } from "./game-object";
import { Nest } from "./nest";
import { Player } from "./player";
import { Spider } from "./spider";
import { Spiderling } from "./spiderling";
import { Spitter } from "./spitter";
import { Weaver } from "./weaver";
import { Web } from "./web";

import { AI } from "./ai";
import { SpidersGame } from "./game";
import { SpidersGameManager } from "./game-manager";
import { SpidersGameSettingsManager } from "./game-settings";

/** The arguments used to construct a BroodMother. */
export type BroodMotherArgs = FirstArgumentFromConstructor<typeof BroodMother>;

/** The arguments used to construct a Cutter. */
export type CutterArgs = FirstArgumentFromConstructor<typeof Cutter>;

/** The arguments used to construct a Nest. */
export type NestArgs = FirstArgumentFromConstructor<typeof Nest>;

/** The arguments used to construct a Spider. */
export type SpiderArgs = FirstArgumentFromConstructor<typeof Spider>;

/** The arguments used to construct a Spiderling. */
export type SpiderlingArgs = FirstArgumentFromConstructor<typeof Spiderling>;

/** The arguments used to construct a Spitter. */
export type SpitterArgs = FirstArgumentFromConstructor<typeof Spitter>;

/** The arguments used to construct a Weaver. */
export type WeaverArgs = FirstArgumentFromConstructor<typeof Weaver>;

/** The arguments used to construct a Web. */
export type WebArgs = FirstArgumentFromConstructor<typeof Web>;

/**
 * The factory that **must** be used to create any game objects in
 * the Spiders game.
 */
export class SpidersGameObjectFactory extends BaseGameObjectFactory {
    /**
     * Creates a new BroodMother in the Game and tracks it for all players.
     *
     * @param args - Data about the BroodMother to set. Any keys matching a
     * property in the game object's class will be automatically set for you.
     * @returns A new BroodMother hooked up in the game and ready for you to
     * use.
     */
    public broodMother<T extends BroodMotherArgs>(
        args: Readonly<T>,
    ): BroodMother & T {
        return this.createGameObject("BroodMother", BroodMother, args);
    }

    /**
     * Creates a new Cutter in the Game and tracks it for all players.
     *
     * @param args - Data about the Cutter to set. Any keys matching a property
     * in the game object's class will be automatically set for you.
     * @returns A new Cutter hooked up in the game and ready for you to use.
     */
    public cutter<T extends CutterArgs>(args: Readonly<T>): Cutter & T {
        return this.createGameObject("Cutter", Cutter, args);
    }

    /**
     * Creates a new Nest in the Game and tracks it for all players.
     *
     * @param args - Data about the Nest to set. Any keys matching a property in
     * the game object's class will be automatically set for you.
     * @returns A new Nest hooked up in the game and ready for you to use.
     */
    public nest<T extends NestArgs>(args: Readonly<T>): Nest & T {
        return this.createGameObject("Nest", Nest, args);
    }

    /**
     * Creates a new Spider in the Game and tracks it for all players.
     *
     * @param args - Data about the Spider to set. Any keys matching a property
     * in the game object's class will be automatically set for you.
     * @returns A new Spider hooked up in the game and ready for you to use.
     */
    public spider<T extends SpiderArgs>(args: Readonly<T>): Spider & T {
        return this.createGameObject("Spider", Spider, args);
    }

    /**
     * Creates a new Spiderling in the Game and tracks it for all players.
     *
     * @param args - Data about the Spiderling to set. Any keys matching a
     * property in the game object's class will be automatically set for you.
     * @returns A new Spiderling hooked up in the game and ready for you to use.
     */
    public spiderling<T extends SpiderlingArgs>(
        args: Readonly<T>,
    ): Spiderling & T {
        return this.createGameObject("Spiderling", Spiderling, args);
    }

    /**
     * Creates a new Spitter in the Game and tracks it for all players.
     *
     * @param args - Data about the Spitter to set. Any keys matching a property
     * in the game object's class will be automatically set for you.
     * @returns A new Spitter hooked up in the game and ready for you to use.
     */
    public spitter<T extends SpitterArgs>(args: Readonly<T>): Spitter & T {
        return this.createGameObject("Spitter", Spitter, args);
    }

    /**
     * Creates a new Weaver in the Game and tracks it for all players.
     *
     * @param args - Data about the Weaver to set. Any keys matching a property
     * in the game object's class will be automatically set for you.
     * @returns A new Weaver hooked up in the game and ready for you to use.
     */
    public weaver<T extends WeaverArgs>(args: Readonly<T>): Weaver & T {
        return this.createGameObject("Weaver", Weaver, args);
    }

    /**
     * Creates a new Web in the Game and tracks it for all players.
     *
     * @param args - Data about the Web to set. Any keys matching a property in
     * the game object's class will be automatically set for you.
     * @returns A new Web hooked up in the game and ready for you to use.
     */
    public web<T extends WebArgs>(args: Readonly<T>): Web & T {
        return this.createGameObject("Web", Web, args);
    }
}

/**
 * The shared namespace for Spiders that is used to
 * initialize each game instance.
 */
export const Namespace = makeNamespace({
    AI,
    Game: SpidersGame,
    GameManager: SpidersGameManager,
    GameObjectFactory: SpidersGameObjectFactory,
    GameSettingsManager: SpidersGameSettingsManager,
    Player,

    // These are generated metadata that allow delta-merging values from
    // clients.
    // They are never intended to be directly interfaced with outside of the
    // Cerveau core developers.
    gameName: "Spiders",
    gameSettingsManager: new SpidersGameSettingsManager(),
    gameObjectsSchema: {
        AI: {
            attributes: {},
            functions: {
                runTurn: {
                    args: [],
                    returns: {
                        typeName: "boolean",
                    },
                },
            },
        },
        Game: {
            attributes: {
                currentPlayer: {
                    typeName: "gameObject",
                    gameObjectClass: Player,
                    nullable: false,
                },
                currentTurn: {
                    typeName: "int",
                },
                cutSpeed: {
                    typeName: "int",
                },
                eggsScalar: {
                    typeName: "float",
                },
                gameObjects: {
                    typeName: "dictionary",
                    keyType: {
                        typeName: "string",
                    },
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: GameObject,
                        nullable: false,
                    },
                },
                initialWebStrength: {
                    typeName: "int",
                },
                maxTurns: {
                    typeName: "int",
                },
                maxWebStrength: {
                    typeName: "int",
                },
                movementSpeed: {
                    typeName: "int",
                },
                nests: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Nest,
                        nullable: false,
                    },
                },
                players: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Player,
                        nullable: false,
                    },
                },
                session: {
                    typeName: "string",
                },
                spitSpeed: {
                    typeName: "int",
                },
                timeAddedPerTurn: {
                    typeName: "int",
                },
                weavePower: {
                    typeName: "int",
                },
                weaveSpeed: {
                    typeName: "int",
                },
                webs: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Web,
                        nullable: false,
                    },
                },
            },
            functions: {},
        },
        BroodMother: {
            parentClassName: "Spider",
            attributes: {
                eggs: {
                    typeName: "int",
                },
                health: {
                    typeName: "int",
                },
            },
            functions: {
                consume: {
                    args: [
                        {
                            argName: "spiderling",
                            typeName: "gameObject",
                            gameObjectClass: Spiderling,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
                spawn: {
                    args: [
                        {
                            argName: "spiderlingType",
                            typeName: "string",
                            defaultValue: "Spitter",
                            literals: ["Spitter", "Weaver", "Cutter"],
                        },
                    ],
                    invalidValue: undefined,
                    returns: {
                        typeName: "gameObject",
                        gameObjectClass: Spiderling,
                        nullable: true,
                    },
                },
            },
        },
        Cutter: {
            parentClassName: "Spiderling",
            attributes: {
                cuttingWeb: {
                    typeName: "gameObject",
                    gameObjectClass: Web,
                    nullable: true,
                },
            },
            functions: {
                cut: {
                    args: [
                        {
                            argName: "web",
                            typeName: "gameObject",
                            gameObjectClass: Web,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
            },
        },
        GameObject: {
            attributes: {
                gameObjectName: {
                    typeName: "string",
                },
                id: {
                    typeName: "string",
                },
                logs: {
                    typeName: "list",
                    valueType: {
                        typeName: "string",
                    },
                },
            },
            functions: {
                log: {
                    args: [
                        {
                            argName: "message",
                            typeName: "string",
                        },
                    ],
                    returns: {
                        typeName: "void",
                    },
                },
            },
        },
        Nest: {
            parentClassName: "GameObject",
            attributes: {
                controllingPlayer: {
                    typeName: "gameObject",
                    gameObjectClass: Player,
                    nullable: true,
                },
                spiders: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Spider,
                        nullable: false,
                    },
                },
                webs: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Web,
                        nullable: false,
                    },
                },
                x: {
                    typeName: "int",
                },
                y: {
                    typeName: "int",
                },
            },
            functions: {},
        },
        Player: {
            parentClassName: "GameObject",
            attributes: {
                broodMother: {
                    typeName: "gameObject",
                    gameObjectClass: BroodMother,
                    nullable: false,
                },
                clientType: {
                    typeName: "string",
                },
                lost: {
                    typeName: "boolean",
                },
                maxSpiderlings: {
                    typeName: "int",
                },
                name: {
                    typeName: "string",
                },
                numberOfNestsControlled: {
                    typeName: "int",
                },
                opponent: {
                    typeName: "gameObject",
                    gameObjectClass: Player,
                    nullable: false,
                },
                reasonLost: {
                    typeName: "string",
                },
                reasonWon: {
                    typeName: "string",
                },
                spiders: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Spider,
                        nullable: false,
                    },
                },
                timeRemaining: {
                    typeName: "float",
                },
                won: {
                    typeName: "boolean",
                },
            },
            functions: {},
        },
        Spider: {
            parentClassName: "GameObject",
            attributes: {
                isDead: {
                    typeName: "boolean",
                },
                nest: {
                    typeName: "gameObject",
                    gameObjectClass: Nest,
                    nullable: true,
                },
                owner: {
                    typeName: "gameObject",
                    gameObjectClass: Player,
                    nullable: false,
                },
            },
            functions: {},
        },
        Spiderling: {
            parentClassName: "Spider",
            attributes: {
                busy: {
                    typeName: "string",
                    defaultValue: "",
                    literals: [
                        "",
                        "Moving",
                        "Attacking",
                        "Strengthening",
                        "Weakening",
                        "Cutting",
                        "Spitting",
                    ],
                },
                movingOnWeb: {
                    typeName: "gameObject",
                    gameObjectClass: Web,
                    nullable: true,
                },
                movingToNest: {
                    typeName: "gameObject",
                    gameObjectClass: Nest,
                    nullable: true,
                },
                numberOfCoworkers: {
                    typeName: "int",
                },
                workRemaining: {
                    typeName: "float",
                },
            },
            functions: {
                attack: {
                    args: [
                        {
                            argName: "spiderling",
                            typeName: "gameObject",
                            gameObjectClass: Spiderling,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
                move: {
                    args: [
                        {
                            argName: "web",
                            typeName: "gameObject",
                            gameObjectClass: Web,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
            },
        },
        Spitter: {
            parentClassName: "Spiderling",
            attributes: {
                spittingWebToNest: {
                    typeName: "gameObject",
                    gameObjectClass: Nest,
                    nullable: true,
                },
            },
            functions: {
                spit: {
                    args: [
                        {
                            argName: "nest",
                            typeName: "gameObject",
                            gameObjectClass: Nest,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
            },
        },
        Weaver: {
            parentClassName: "Spiderling",
            attributes: {
                strengtheningWeb: {
                    typeName: "gameObject",
                    gameObjectClass: Web,
                    nullable: true,
                },
                weakeningWeb: {
                    typeName: "gameObject",
                    gameObjectClass: Web,
                    nullable: true,
                },
            },
            functions: {
                strengthen: {
                    args: [
                        {
                            argName: "web",
                            typeName: "gameObject",
                            gameObjectClass: Web,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
                weaken: {
                    args: [
                        {
                            argName: "web",
                            typeName: "gameObject",
                            gameObjectClass: Web,
                            nullable: false,
                        },
                    ],
                    invalidValue: false,
                    returns: {
                        typeName: "boolean",
                    },
                },
            },
        },
        Web: {
            parentClassName: "GameObject",
            attributes: {
                length: {
                    typeName: "float",
                },
                load: {
                    typeName: "int",
                },
                nestA: {
                    typeName: "gameObject",
                    gameObjectClass: Nest,
                    nullable: true,
                },
                nestB: {
                    typeName: "gameObject",
                    gameObjectClass: Nest,
                    nullable: true,
                },
                spiderlings: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Spiderling,
                        nullable: false,
                    },
                },
                strength: {
                    typeName: "int",
                },
            },
            functions: {},
        },
    },
    gameVersion:
        "a8df6038306b6855bb35959d7698f8dcbf98f48e7e148de59fef940ccb241bdf",
});
