// Generated by Creer at 12:50AM on April 14, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
// Note: You should never modify this file... probably.

var serializer = require(__basedir + "/gameplay/serializer");

var classes = {};

classes.Game = require("./game");

classes.Game._deltaMergeableProperties = {
    currentPlayer: {
        type: {"keyType": null, "name": "Player", "valueType": null},
        defaultValue: null,
    },

    currentTurn: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

    gameObjects: {
        type: {"keyType": {"keyType": null, "name": "string", "valueType": null}, "name": "dictionary", "valueType": {"keyType": null, "name": "GameObject", "valueType": null}},
        defaultValue: {},
    },

    maxTurns: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 100,
    },

    moves: {
        type: {"keyType": null, "name": "list", "valueType": {"keyType": null, "name": "Move", "valueType": null}},
        defaultValue: [],
    },

    pieces: {
        type: {"keyType": null, "name": "list", "valueType": {"keyType": null, "name": "Piece", "valueType": null}},
        defaultValue: [],
    },

    players: {
        type: {"keyType": null, "name": "list", "valueType": {"keyType": null, "name": "Player", "valueType": null}},
        defaultValue: [],
    },

    session: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    turnsToDraw: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

};


classes.Game.aiFinished_runTurn.cerveau = {
    args: [
    ],
    returns: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: true,
    },
};

//<<-- Creer-Merge: secret-Game -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Game -->>


classes.GameObject = require("./gameObject");

classes.GameObject._deltaMergeableProperties = {
    gameObjectName: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    id: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    logs: {
        type: {"keyType": null, "name": "list", "valueType": {"keyType": null, "name": "string", "valueType": null}},
        defaultValue: [],
    },

};


classes.GameObject.log.cerveau = {
    args: [
        {
            name: "message",
            type: {"keyType": null, "name": "string", "valueType": null},
        },
    ],
    returns: undefined,
};

//<<-- Creer-Merge: secret-GameObject -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-GameObject -->>


classes.Move = require("./move");

classes.Move._deltaMergeableProperties = {
    captured: {
        type: {"keyType": null, "name": "Piece", "valueType": null},
        defaultValue: null,
    },

    fromFile: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    fromRank: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

    piece: {
        type: {"keyType": null, "name": "Piece", "valueType": null},
        defaultValue: null,
    },

    promotion: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    san: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    toFile: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    toRank: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

};


//<<-- Creer-Merge: secret-Move -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Move -->>


classes.Piece = require("./piece");

classes.Piece._deltaMergeableProperties = {
    captured: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

    file: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    hasMoved: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

    owner: {
        type: {"keyType": null, "name": "Player", "valueType": null},
        defaultValue: null,
    },

    rank: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

    type: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

};


classes.Piece.move.cerveau = {
    args: [
        {
            name: "file",
            type: {"keyType": null, "name": "string", "valueType": null},
        },
        {
            name: "rank",
            type: {"keyType": null, "name": "int", "valueType": null},
        },
        {
            name: "promotionType",
            type: {"keyType": null, "name": "string", "valueType": null},
            defaultValue: "",
        },
    ],
    returns: {
        type: {"keyType": null, "name": "Move", "valueType": null},
        defaultValue: null,
    },
};

//<<-- Creer-Merge: secret-Piece -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Piece -->>


classes.Player = require("./player");

classes.Player._deltaMergeableProperties = {
    clientType: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    color: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    inCheck: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

    lost: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

    madeMove: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

    name: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "Anonymous",
    },

    otherPlayer: {
        type: {"keyType": null, "name": "Player", "valueType": null},
        defaultValue: null,
    },

    pieces: {
        type: {"keyType": null, "name": "list", "valueType": {"keyType": null, "name": "Piece", "valueType": null}},
        defaultValue: [],
    },

    rankDirection: {
        type: {"keyType": null, "name": "int", "valueType": null},
        defaultValue: 0,
    },

    reasonLost: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    reasonWon: {
        type: {"keyType": null, "name": "string", "valueType": null},
        defaultValue: "",
    },

    timeRemaining: {
        type: {"keyType": null, "name": "float", "valueType": null},
        defaultValue: 0,
    },

    won: {
        type: {"keyType": null, "name": "boolean", "valueType": null},
        defaultValue: false,
    },

};


//<<-- Creer-Merge: secret-Player -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

classes.Player.getMoves.cerveau = {
    args: [],
    returns: {
        type: {name: "dictionary"},
        defaultValue: {},
    },
    isSecret: true,
},

//<<-- /Creer-Merge: secret-Player -->>


// Hook up the game's internal classes that we just finished initializing
classes.Game.classes = classes;
classes.Game.prototype.classes = classes;

module.exports = classes.Game;
