// Generated by Creer at 05:17PM on April 08, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
// Note: You should never modify this file... probably.

var serializer = require(__basedir + "/gameplay/serializer");

var classes = {};

classes.Game = require("./game");

classes.Game.aiFinished_runTurn.cerveau = {
    args: [
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: true,
    },
};

//<<-- Creer-Merge: secret-Game -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Game -->>


classes.BroodMother = require("./broodMother");

classes.BroodMother.consume.cerveau = {
    args: [
        {
            name: "spiderling",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

classes.BroodMother.spawn.cerveau = {
    args: [
        {
            name: "spiderlingType",
            converter: serializer.defaultString,
        },
    ],
    returns: {
        converter: serializer.defaultGameObject,
        defaultValue: null,
    },
};

//<<-- Creer-Merge: secret-BroodMother -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-BroodMother -->>


classes.Cutter = require("./cutter");

classes.Cutter.cut.cerveau = {
    args: [
        {
            name: "web",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

//<<-- Creer-Merge: secret-Cutter -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Cutter -->>


classes.GameObject = require("./gameObject");

classes.GameObject.log.cerveau = {
    args: [
        {
            name: "message",
            converter: serializer.defaultString,
        },
    ],
    returns: undefined,
};

//<<-- Creer-Merge: secret-GameObject -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-GameObject -->>


classes.Nest = require("./nest");

//<<-- Creer-Merge: secret-Nest -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Nest -->>


classes.Player = require("./player");

//<<-- Creer-Merge: secret-Player -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Player -->>


classes.Spider = require("./spider");

//<<-- Creer-Merge: secret-Spider -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Spider -->>


classes.Spiderling = require("./spiderling");

classes.Spiderling.attack.cerveau = {
    args: [
        {
            name: "spiderling",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

classes.Spiderling.move.cerveau = {
    args: [
        {
            name: "web",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

//<<-- Creer-Merge: secret-Spiderling -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Spiderling -->>


classes.Spitter = require("./spitter");

classes.Spitter.spit.cerveau = {
    args: [
        {
            name: "nest",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

//<<-- Creer-Merge: secret-Spitter -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Spitter -->>


classes.Weaver = require("./weaver");

classes.Weaver.strengthen.cerveau = {
    args: [
        {
            name: "web",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

classes.Weaver.weaken.cerveau = {
    args: [
        {
            name: "web",
            converter: serializer.defaultGameObject,
        },
    ],
    returns: {
        converter: serializer.defaultBoolean,
        defaultValue: false,
    },
};

//<<-- Creer-Merge: secret-Weaver -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Weaver -->>


classes.Web = require("./web");

//<<-- Creer-Merge: secret-Web -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// if you want to add a "secret" method that clients don't publicly know about, but can call, do so here. Best use case is an easy way for human clients to ask for special game information, otherwise forget this exists.

//<<-- /Creer-Merge: secret-Web -->>


// Hook up the game's internal classes that we just finished initializing
classes.Game.classes = classes;
classes.Game.prototype.classes = classes;

module.exports = classes.Game;
