// Generated by Creer at 05:17PM on April 08, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'

var Class = require(__basedir + "/utilities/class");
var serializer = require(__basedir + "/gameplay/serializer");
var log = require(__basedir + "/gameplay/log");
var GameObject = require("./gameObject");

//<<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// any additional requires you want can be required here safely between Creer re-runs

//<<-- /Creer-Merge: requires -->>

// @class Nest: A location (node) connected to other Nests via Webs (edges) in the game that Spiders can converge on, regardless of owner.
var Nest = Class(GameObject, {
    /**
     * Initializes Nests.
     *
     * @param {Object} data - a simple mapping passsed in to the constructor with whatever you sent with it. GameSettings are in here by key/value as well.
     */
    init: function(data) {
        GameObject.init.apply(this, arguments);

        /**
         * All the Spiders currently located on this Nest.
         *
         * @type {list.<Spider>}
         */
        this._addProperty("spiders", serializer.defaultArray(data.spiders));

        /**
         * Webs that connect to this Nest.
         *
         * @type {list.<Web>}
         */
        this._addProperty("webs", serializer.defaultArray(data.webs));

        /**
         * The X coordinate of the Nest. Used for distance calculations.
         *
         * @type {number}
         */
        this._addProperty("x", serializer.defaultInteger(data.x));

        /**
         * The Y coordinate of the Nest. Used for distance calculations.
         *
         * @type {number}
         */
        this._addProperty("y", serializer.defaultInteger(data.y));


        //<<-- Creer-Merge: init -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

        // put any initialization logic here. the base variables should be set from 'data' above
        // NOTE: no players are connected (nor created) at this point. For that logic use 'begin()'

        //<<-- /Creer-Merge: init -->>
    },

    gameObjectName: "Nest",


    //<<-- Creer-Merge: added-functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

    // You can add additional functions here. These functions will not be directly callable by client AIs

    distanceTo: function(otherNest) {
        return Math.euclideanDistance(this, otherNest);
    },

    //<<-- /Creer-Merge: added-functions -->>

});

module.exports = Nest;
