// Generated by Creer at 10:09PM on April 07, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'

var Class = require(__basedir + "/utilities/class");
var serializer = require(__basedir + "/gameplay/serializer");
var log = require(__basedir + "/gameplay/log");
var GameObject = require("./gameObject");

//<<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

// any additional requires you want can be required here safely between Creer re-runs

//<<-- /Creer-Merge: requires -->>

// @class Web: A connection (edge) to a Nest (node) in the game that Spiders can converge on (regardless of owner). Spiders can travel in either direction on Webs.
var Web = Class(GameObject, {
    /**
     * Initializes Webs.
     *
     * @param {Object} data - a simple mapping passsed in to the constructor with whatever you sent with it. GameSettings are in here by key/value as well.
     */
    init: function(data) {
        GameObject.init.apply(this, arguments);

        /**
         * How long this Web is, i.e., the distance between its nestA and nestB.
         *
         * @type {number}
         */
        this._addProperty("length", serializer.defaultNumber(data.length));

        /**
         * How much weight this Web currently has on it, which is the sum of all its Spiderlings weight.
         *
         * @type {number}
         */
        this._addProperty("load", serializer.defaultInteger(data.load));

        /**
         * The first Nest this Web is connected to.
         *
         * @type {Nest}
         */
        this._addProperty("nestA", serializer.defaultGameObject(data.nestA));

        /**
         * The second Nest this Web is connected to.
         *
         * @type {Nest}
         */
        this._addProperty("nestB", serializer.defaultGameObject(data.nestB));

        /**
         * All the Spiderlings currently moving along this Web.
         *
         * @type {list.<Spiderling>}
         */
        this._addProperty("spiderlings", serializer.defaultArray(data.spiderlings));

        /**
         * How much weight this Web can take before snapping and destroying itself and all the Spiders on it.
         *
         * @type {number}
         */
        this._addProperty("strength", serializer.defaultInteger(data.strength));


        //<<-- Creer-Merge: init -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

        // put any initialization logic here. the base variables should be set from 'data' above

        this.game.webs.push(this);
        this.nestA.webs.push(this);
        this.nestB.webs.push(this);
        this.length = this.nestA.distanceTo(this.nestB);
        this.strength = 100;
        this._maxStrength = Infinity;

        //<<-- /Creer-Merge: init -->>
    },

    gameObjectName: "Web",


    //<<-- Creer-Merge: added-functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

    /**
     * Snaps the web, killing all spiders on it.
     */
    snap : function() {
        var spiderlings = this.spiderlings.clone();
        for(var i = spiderlings.length - 1; i >= 0; i--) { // reverse order as they will remove themselves from the end of the list, so we don't have to shift everything n times
            spiderlings[i].kill();
        }

        this.strength = -1;

        this.game.webs.removeElement(this);

        this.nestA.webs.removeElement(this);
        this.nestA = null;

        this.nestB.webs.removeElement(this);
        this.nestB = null;
    },

    /**
     * Checks if the Web is connected to some Nest
     *
     * @param {Nest} nest - nest to check if is connected to at nestA or nestB
     * @param {Nest} [otherNest] - if passed then checks if nestA and nestB are otherNest and the previous arg nest (in either order)
     * @returns {boolean|undefined} True if it is connected to that web, false otherwise, undefined if nest is null.
     */
    isConnectedTo: function(nest, otherNest) {
        if(!nest) {
            return undefined;
        }

        if(!otherNest) {
            return this.nestA === nest || this.nestB === nest;
        }
        else {
            return (this.nestA === nest && this.nestB === otherNest) || (this.nestA === otherNest && this.nestB === nest);
        }
    },

    /**
     * Gets the other nest, given one of its nests A or B
     *
     * @param {Nest} nest - the nest to get the other one
     * @returns {Nest|undefined} the other Nest that the passed in nest is not, undefined is nest is not part of this Web.
     */
    getOtherNest: function(nest) {
        if(!this.isConnectedTo(nest)) {
            return undefined;
        }

        return this.nestA === nest ? this.nestB : this.nestA;
    },

    /**
     * Should be called whenever something changes on the web, so it need to re-calculate its current load and maybe snap.
     *
     * @param {number} num - the load (weight) of a spiderling to add
     */
    addLoad: function(num) {
        this.load = Math.Max(this.load + num, 0);

        if(this.load >= this.strength) {
            this.snap();
        }
    },

    /**
     * Adds some number to this web's strength, and might snap it
     *
     * @param {number} num - number to add to this Web's strength
     */
    addStrength: function(num) {
        this.strength = Math.clamp(this.strength + num, 1, this._maxStrength);

        if(this.load >= this.strength) {
            this.snap();
        }
    },


    // You can add additional functions here. These functions will not be directly callable by client AIs

    //<<-- /Creer-Merge: added-functions -->>

});

module.exports = Web;
