// WARNING: Here be Dragons
// This file is generated by Creer, do not modify it
// It basically sets up all the classes, interfaces, types, and what-not that
// we need for TypeScript to know the base classes, while allowing for minimal
// code for developers to be forced to fill out.

/* eslint-disable @typescript-eslint/no-empty-interface */

// base game classes
import {
    BaseAI,
    BaseGame,
    BaseGameManager,
    BaseGameObject,
    BaseGameObjectFactory,
    BaseGameSettingsManager,
    BasePlayer,
    makeNamespace,
} from "~/core/game";

// mixins
import { TwoPlayerPlayer, mixTwoPlayer } from "~/core/game/mixins";

/**
 * The interface that the Player for the JungleChess game
 * must implement from mixed in game logic.
 */
export interface BaseJungleChessPlayer extends BasePlayer, TwoPlayerPlayer {}

const base0 = {
    AI: BaseAI,
    Game: BaseGame,
    GameManager: BaseGameManager,
    GameObject: BaseGameObject,
    GameSettings: BaseGameSettingsManager,
};

const base1 = mixTwoPlayer(base0);

const mixed = base1;

/** The base AI class for the JungleChess game will mixin logic. */
class BaseJungleChessAI extends mixed.AI {}

/** The base Game class for the JungleChess game will mixin logic. */
class BaseJungleChessGame extends mixed.Game {}

/** The base GameManager class for the JungleChess game will mixin logic. */
class BaseJungleChessGameManager extends mixed.GameManager {}

/** The base GameObject class for the JungleChess game will mixin logic. */
class BaseJungleChessGameObject extends mixed.GameObject {}

/** The base GameSettings class for the JungleChess game will mixin logic. */
class BaseJungleChessGameSettings extends mixed.GameSettings {}

/** The Base classes that game classes build off of. */
export const BaseClasses = {
    AI: BaseJungleChessAI,
    Game: BaseJungleChessGame,
    GameManager: BaseJungleChessGameManager,
    GameObject: BaseJungleChessGameObject,
    GameSettings: BaseJungleChessGameSettings,
};

// Now all the base classes are created;
// so we can start importing/exporting the classes that need them.

/** All the possible properties for GameObject instances. */
export interface GameObjectProperties {}

/** All the possible properties for Player instances. */
export interface PlayerProperties {
    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other
     * language. For potential data mining purposes.
     */
    clientType?: string;

    /**
     * Player b will always start first.
     */
    color?: "b" | "r";

    /**
     * If the player lost the game or not.
     */
    lost?: boolean;

    /**
     * The name of the player.
     */
    name?: string;

    /**
     * This player's opponent in the game.
     */
    opponent?: Player;

    /**
     * The reason why the player lost the game.
     */
    reasonLost?: string;

    /**
     * The reason why the player won the game.
     */
    reasonWon?: string;

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    timeRemaining?: number;

    /**
     * If the player won the game or not.
     */
    won?: boolean;
}

/**
 * The default args passed to a constructor function for class
 * instances of GameObject.
 */
export type GameObjectConstructorArgs<
    T extends Record<string, unknown> = Record<string, unknown>
> = Readonly<GameObjectProperties & T>;

/**
 * The default args passed to a constructor function for class
 * instances of Player.
 */
export type PlayerConstructorArgs<
    T extends Record<string, unknown> = Record<string, unknown>
> = Readonly<BaseJungleChessPlayer & PlayerProperties & T>;

export * from "./game-object";
export * from "./player";
export * from "./game";
export * from "./game-manager";
export * from "./ai";

import { GameObject } from "./game-object";
import { Player } from "./player";

import { AI } from "./ai";
import { JungleChessGame } from "./game";
import { JungleChessGameManager } from "./game-manager";
import { JungleChessGameSettingsManager } from "./game-settings";

/**
 * The factory that **must** be used to create any game objects in
 * the JungleChess game.
 */
export class JungleChessGameObjectFactory extends BaseGameObjectFactory {}

/**
 * The shared namespace for JungleChess that is used to
 * initialize each game instance.
 */
export const Namespace = makeNamespace({
    AI,
    Game: JungleChessGame,
    GameManager: JungleChessGameManager,
    GameObjectFactory: JungleChessGameObjectFactory,
    GameSettingsManager: JungleChessGameSettingsManager,
    Player,

    // These are generated metadata that allow delta-merging values from
    // clients.
    // They are never intended to be directly interfaced with outside of the
    // Cerveau core developers.
    gameName: "JungleChess",
    gameSettingsManager: new JungleChessGameSettingsManager(),
    gameObjectsSchema: {
        AI: {
            attributes: {},
            functions: {
                makeMove: {
                    args: [],
                    returns: {
                        typeName: "string",
                    },
                },
            },
        },
        Game: {
            attributes: {
                gameObjects: {
                    typeName: "dictionary",
                    keyType: {
                        typeName: "string",
                    },
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: GameObject,
                        nullable: false,
                    },
                },
                history: {
                    typeName: "list",
                    valueType: {
                        typeName: "string",
                    },
                },
                jungleFen: {
                    typeName: "string",
                },
                players: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Player,
                        nullable: false,
                    },
                },
                session: {
                    typeName: "string",
                },
            },
            functions: {},
        },
        GameObject: {
            attributes: {
                gameObjectName: {
                    typeName: "string",
                },
                id: {
                    typeName: "string",
                },
                logs: {
                    typeName: "list",
                    valueType: {
                        typeName: "string",
                    },
                },
            },
            functions: {
                log: {
                    args: [
                        {
                            argName: "message",
                            typeName: "string",
                        },
                    ],
                    returns: {
                        typeName: "void",
                    },
                },
            },
        },
        Player: {
            parentClassName: "GameObject",
            attributes: {
                clientType: {
                    typeName: "string",
                },
                color: {
                    typeName: "string",
                    defaultValue: "b",
                    literals: ["b", "r"],
                },
                lost: {
                    typeName: "boolean",
                },
                name: {
                    typeName: "string",
                },
                opponent: {
                    typeName: "gameObject",
                    gameObjectClass: Player,
                    nullable: false,
                },
                reasonLost: {
                    typeName: "string",
                },
                reasonWon: {
                    typeName: "string",
                },
                timeRemaining: {
                    typeName: "float",
                },
                won: {
                    typeName: "boolean",
                },
            },
            functions: {},
        },
    },
    gameVersion:
        "0f0b85b33f03a669a391b36c90daa195d028dd1f21f8d4b601adfcf39b23eee2",
});
