// Generated by Creer, git hash 1003b60e7d8167f4f73211921de0a0516d97a782
// Note: this is the file you should modify. The logic generated by Creer should be mostly in ./generated/
var Class = require("../../utilities/class");
var GeneratedGameObject = require("./generated/generatedGameObject");

// @class GameObject: An object in the game. The most basic class that all game classes should inherit from automatically.
var GameObject = Class(GeneratedGameObject, {
	init: function(data) {
		GeneratedGameObject.init.apply(this, arguments);

		// put any initialization logic here. the base variables should be set from 'data' in GeneratedGameObject's init function
	},

});

module.exports = GameObject;
