// Generated by Creer, git hash fa0ddf38a9de12f1ec780817a1333033da78ca83
// Note: this is the file you should modify. The logic generated by Creer should be mostly in ./generated/
var Class = require("../../utilities/class");
var GeneratedGameObject = require("./generated/generatedGameObject");

// @class GameObject: An object in the game. The most basic class that all game classes should inherit from automatically.
var GameObject = Class(GeneratedGameObject, {
	init: function(data) {
		GeneratedGameObject.init.apply(this, arguments);

		// put any initialization logic here. the base variables should be set from 'data' in GeneratedGameObject's init function
	},

});

module.exports = GameObject;
