// Generated by Creer at 02:31PM on October 26, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
// Note: You should never modify this file.

var GameManager = require(__basedir + "/gameplay/shared/gameManager");
var serializer = require(__basedir + "/gameplay/serializer");

/**
 * An instance of the base GameManager class, given the structure of this Checkers game so it can manage the game safely.
 */
var checkersGameManager = new GameManager({
    Game: {
        name: "Checkers",
    },

    AI: {
        runTurn: {
            args: [
            ],
            returns: {
                converter: serializer.defaultBoolean,
                defaultValue: true,
            },
        },
    },

    Checker: {
        isMine: {
            args: [
            ],
            returns: {
                converter: serializer.defaultBoolean,
                defaultValue: false,
            },
        },
        move: {
            args: [
                {
                    name: "x",
                    converter: serializer.defaultInteger,
                },
                {
                    name: "y",
                    converter: serializer.defaultInteger,
                },
            ],
            returns: {
                converter: serializer.defaultGameObject,
                defaultValue: null,
            },
        },
    },

    GameObject: {
        log: {
            args: [
                {
                    name: "message",
                    converter: serializer.defaultString,
                },
            ],
            returns: undefined,
        },
    },

    Player: {
    },
});

module.exports = checkersGameManager;
