// Generated by Creer, git hash Error: git probably not installed
// Note: this is the file you should modify. The logic generated be Creer should be mostly in generated/
var Class = require("../../structures/class");
var GeneratedGameObject = require("./generated/generatedGameObject")

// @class GameObject: An object in the game. The most basic class that all game classes should inherit from automatically.
module.exports = Class(GeneratedGameObject, {
	init: function(game, data) {
		GeneratedGameObject.init.apply(this, arguments);

		// put any initialization logic here. the base variables should be set from 'data' in GeneratedGameObject's init function
	},

});
